#!/usr/bin/env python3
"""vol_sizing_overlay_study.py — candidate #10: vol-targeted sizing overlay.

The ONLY price-only-EXEMPT candidate: it does not add a new signal, it re-sizes the
SAME live short bet to target constant risk, aiming to raise the book's Sharpe/DSR.
Per `results/strategy_candidates_2026-06-10.md` (#10) + Phase 4.

INPUT: results/live_journals/<SYM>-*.jsonl — live-config short trades (ema_mode true,
target_rr 6.0, side short, max-hold 504, 4H, fee10/slip5, funding) generated by
scripts/gen_live_journals.sh. Each close event has pnl_usd, notional_usd, entry, stop,
ts (open) + ts (close).

THE BET
-------
Current sizing = fixed $ risk per trade (stake/stop_distance). Trades opened in
high-vol regimes carry more $ PnL variance → the book's risk is concentrated in vol
spikes. Re-weight each trade so each contributes EQUAL risk: weight_i ∝ 1 / vol_i,
where vol_i = realized vol at entry (proxied by stop_distance/entry, the wick width
the live config already uses). Compare the portfolio Sharpe of equal-$ vs vol-targeted.

================================  PRE-REGISTRATION  ============================
  Risk proxy:        stop_distance/entry per trade (the live wick stop = a vol read).
  Sizing variants:   (1) BASELINE = as-traded ($ risk fixed; weight 1 each).
                     (2) VOLTGT = weight ∝ 1/risk_proxy, normalized to same gross.
                     (3) INVNOTIONAL = weight ∝ 1/notional (alt risk read).
  Return unit:       per-trade return = pnl_usd / notional_usd (return on capital).
  Portfolio series:  sum weighted returns per close-date; daily-ish; annualize Sharpe.
  ACCEPT:            VOLTGT raises Sharpe by a MEANINGFUL margin (>= +0.2 absolute) AND
                     does not just lever beta. Report both. Price-only-exempt so the
                     overfit-DSR question is "does it improve the existing book", not a
                     new trial.
===============================================================================
"""
import os, glob, json, math, datetime
from collections import defaultdict
import numpy as np

JDIR = "results/live_journals"


def load_trades():
    """list of dicts: {sym, open_ts, close_ts, ret, risk_proxy, notional, pnl}."""
    trades = []
    opens = {}
    for fp in glob.glob(os.path.join(JDIR, "*.jsonl")):
        with open(fp) as f:
            for line in f:
                try:
                    e = json.loads(line)
                except json.JSONDecodeError:
                    continue
                sym = e.get("symbol")
                if e.get("event") == "open":
                    opens[(sym, e["ts"])] = e
                elif e.get("event") == "close":
                    entry = e.get("entry", 0); stop = e.get("stop", 0)
                    notional = e.get("notional_usd", 0); pnl = e.get("pnl_usd", 0)
                    if entry <= 0 or notional <= 0:
                        continue
                    risk = abs(stop - entry) / entry if entry > 0 else None
                    if not risk or risk <= 0:
                        continue
                    try:
                        cts = datetime.datetime.fromisoformat(e["ts"].replace("Z", "+00:00"))
                    except Exception:
                        continue
                    trades.append(dict(sym=sym, close=cts, ret=pnl / notional,
                                       risk=risk, notional=notional, pnl=pnl))
    trades.sort(key=lambda t: t["close"])
    return trades


def portfolio_sharpe(trades, weight_fn):
    """Aggregate weighted per-trade returns into a daily series, annualized Sharpe.
    weight_fn(t) -> relative weight; normalized so mean weight = 1."""
    w = np.array([weight_fn(t) for t in trades], dtype=float)
    w = w / w.mean()                       # same gross exposure as baseline
    rets = np.array([t["ret"] for t in trades]) * w
    # bucket by close date -> daily PnL (return units)
    byday = defaultdict(float)
    for t, r in zip(trades, rets):
        byday[t["close"].date()] += r
    series = np.array([byday[d] for d in sorted(byday)])
    if len(series) < 2 or series.std(ddof=1) == 0:
        return 0.0, series
    # trades span ~6y; annualize by trading days present
    ann = math.sqrt(252)
    return series.mean() / series.std(ddof=1) * ann, series


def main():
    trades = load_trades()
    if not trades:
        print("No journals — run scripts/gen_live_journals.sh first."); return
    print("=" * 72)
    print(f"VOL-SIZING OVERLAY (#10) — {len(trades)} live short trades, "
          f"{len(set(t['sym'] for t in trades))} symbols")
    print("=" * 72)

    variants = {
        "BASELINE (as-traded $-risk)": lambda t: 1.0,
        "VOLTGT (w ~ 1/stop_dist)":     lambda t: 1.0 / t["risk"],
        "INVNOTIONAL (w ~ 1/notional)": lambda t: 1.0 / t["notional"],
    }
    print(f"{'variant':<32}{'ann.Sharpe':>11}{'mean_ret':>10}{'totPnL_norm':>12}")
    print("-" * 72)
    base = None
    results = {}
    for name, fn in variants.items():
        sh, series = portfolio_sharpe(trades, fn)
        results[name] = sh
        print(f"{name:<32}{sh:>11.3f}{series.mean()*1e4:>9.2f}b{series.sum():>12.3f}")
        if name.startswith("BASELINE"):
            base = sh

    print()
    print("=" * 72)
    print("VERDICT (candidate #10 vol-sizing overlay)")
    voltgt = results["VOLTGT (w ~ 1/stop_dist)"]
    delta = voltgt - base
    if delta >= 0.2:
        print(f"  CANDIDATE: VOLTGT Sharpe {voltgt:.3f} vs baseline {base:.3f} "
              f"(+{delta:.3f}) — meaningful sizing improvement. Re-check it's not just "
              f"de-levering beta; if real, propose as a sizing change (price-only-exempt).")
    elif delta > 0:
        print(f"  MARGINAL: VOLTGT +{delta:.3f} Sharpe — positive but below the +0.2 bar. "
              f"Not worth a sizing-logic change vs operational simplicity.")
    else:
        print(f"  NO-GO: VOLTGT {voltgt:.3f} does not beat baseline {base:.3f} "
              f"({delta:+.3f}). The live fixed-$-risk sizing already normalizes by stop "
              f"distance (= a vol read), so re-weighting adds nothing.")
    print("=" * 72)


if __name__ == "__main__":
    main()
